### ISSUE TITLE
How do I install Carbon?

### ISSUE THREAD

**Issue by alehandrof** [lesaff/statamic-date_calc#1]
I take it this plugin requires Carbon. Can you please provide some instructions about how to install it so that this add-on can use it?

Per Carbon's installation instructions, I dropped `Carbon.php` in the same add-on folder and then added `require 'Carbon.php';` as a second line to date_calc. But though plausible that didn't work.

**Comment by lesaff** [comment]
Carbon is included with Statamic, so you don't need to install anything.

**Comment by alehandrof** [comment]
The reason I asked is because if I try this:

```
{{ date_calc start_date="2014-11-16 18:00:00" method="subYears" value="5" format="F d, Y" }}
```

I get this error:

>  Fatal error: Call to a member function subYears() on a non-object in /home/[username]/[folder]/statamic/_add-ons/date_calc/pi.date_calc.php on line 87

**Comment by lesaff** [comment]
Ooh, let me take a look at it. Thanks for pointing that out.

**Comment by lesaff** [comment]
I just pushed a fix to the problem. Thanks again for spotting the issue. The add-on will now sanitized any date input to prevent the error.

**Comment by alehandrof** [comment]
Thank you for the quick fix. I'm trying to output an iCalendar file from an `{{ entries:listing }}` and this add-on will come in handy.

**Comment by lesaff** [comment]
That's one of the big reason I created the addon. I needed something to generate a dynamic date range but nothing available.

Glad you find it useful.

Cheers
