### ISSUE TITLE
Calculations between variables

### ISSUE THREAD

**Issue by wesort** [lesaff/statamic-date_calc#3]
I'd like to render the difference in hours and minutes between to date-times.

An example entry has:
```
timesheet_start: '2018-11-13T22:00'
timesheet_end: '2018-11-13T23:30'
```

Is this addon setup for this? My thinking on the syntax would be:
```
{{ date_calc start_date="{ timesheet_start }" end_date="{ timesheet_end }" method="subHours" format="H:i" }}
```

Also, I'm on Statamic v2.10.5 and the example from [How to use](https://github.com/lesaff/statamic-date_calc#how-to-use) doesn't render anything??

Thanks.

**Comment by lesaff** [comment]
@wesort, this addon is for v1.x. 
It should be pretty straight forward to port to v2 except that we don't use Statamic anymore.

**Comment by wesort** [comment]
Ah, I see. 

I'm not a php dev so wouldn't know where to start to port it to v2. I kind-of feel this could benefit core Statamic though so I'll put in a FR for _[date calculation modifiers](https://docs.statamic.com/modifiers#date)_.

Thanks anyway.
